### ISSUE TITLE
indentation incorrect when using braces

### ISSUE THREAD

**Issue by defunctzombie** [wavded/vim-stylus#31]
When I have the following css

``` css
.foo {
    display: none;
}
```

Indent wants to change it to

``` css
.foo {
    display: none;
    }
```

I looked at the stylus.vim indent file but unfortunately don't know jack about writing one of those.
